/*
 * Compatibility layer for libecc internal consistency checks
 * This symbol is generated by libecc internal macros during compilation
 * but may not be available in all build configurations
 */

#include <libecc/nn/nn_config.h>

/*
 * Delegate compatibility checks to the symbol generated by libecc.
 * The recursion guard handles the case where this weak symbol is the
 * only available implementation.
 */
static void call_libecc_consistency_check(void)
{
	static int in_progress;

	if (in_progress != 0) {
		return;
	}

	in_progress = 1;
#ifdef NO_USE_COMPLETE_FORMULAS
	LIBECC_CONCATENATE(nn_consistency_check_maxbitlen, NN_MAX_BASE, wordsize,
			   WORDSIZE, MAX_DIGEST_SIZE)();
#else
	LIBECC_CONCATENATE(nn_consistency_check_maxbitlen, NN_MAX_BASE, wordsize,
			   WORDSIZE, complete_formulas, MAX_DIGEST_SIZE)();
#endif
	in_progress = 0;
}

void __attribute__((weak)) nn_consistency_check_maxbitlen_521_wordsize_64_complete_formulas_114(void)
{
	call_libecc_consistency_check();
}

void __attribute__((weak)) nn_consistency_check_maxbitlen_521_wordsize_64_114(void)
{
	call_libecc_consistency_check();
}
